"use client";

import { useMemo, useRef, useState } from "react";

import { analyzeResults } from "@/core/results-analysis";
import { resolveRung } from "@/core/rungs";
import type { Simulation } from "@/core/simulation";
import type { ColumnMapping, Rung, SeparationGain } from "@/core/types";
import type { ColumnStats } from "@/csv/infer";
import type { ParsedTable } from "@/csv/parse";
import { buildNamedNumericColumns } from "@/csv/separation-gain-input";
import { ResultsPanel } from "@/static/ResultsPanel";

import { CapabilityLine } from "./CapabilityLine";
import { DatasetPicker } from "./DatasetPicker";
import { MappingPanel } from "./MappingPanel";
import { exportCanvasAsPng } from "./pngExport";
import { PALMER_PENGUINS_CSV, SAMPLE_DATASETS } from "./sample-datasets";
import { SeparationGainDisplay } from "./SeparationGainDisplay";
import { SimulationCanvas } from "./SimulationCanvas";
import { useCapability } from "./useCapability";
import { useReducedMotion } from "./useReducedMotion";
import { buildSimulation, computeSeparationGainForSim, useParsedDataset } from "./useSimulation";
import { RUNG_BUDGETS } from "@/core/rungs";

// Simulation seed (physics init + separation-gain sampling) — independent of
// which sample dataset's own generation seed was used (see src/ui/
// sample-datasets.ts, generated by scripts/gen-samples.mjs).
const DEFAULT_SEED = 1;
// SPEC.md §10: "the page loads directly into sample dataset #1, already
// mid-settle" — sample #1 is the real, cited, permissively-licensed dataset
// (Palmer Penguins), not the synthetic one. See docs/limitations for the
// measured separation-gain result against this exact shipped fixture.
const DEFAULT_CSV = PALMER_PENGUINS_CSV;

interface FrameInfo {
  step: number;
  converged: boolean;
  unstable: boolean;
}

/**
 * Owns its own frame-info + results state, freshly initialized on mount —
 * the parent remounts this (via a `key` built from the mapping + rung)
 * instead of resetting state in an effect. Results (separation-gain +
 * accessible analysis) are computed once, inside the onFrame event
 * callback, the first time convergence is reached — never in an effect body.
 */
function RunningSimulation({ sim, rung, mappings, stats, seed }: { sim: Simulation; rung: Rung; mappings: ColumnMapping[]; stats: ColumnStats[]; seed: number }): React.JSX.Element {
  const [frameInfo, setFrameInfo] = useState<FrameInfo>({ step: 0, converged: false, unstable: false });
  const [gain, setGain] = useState<SeparationGain | null>(null);
  const [exportState, setExportState] = useState<"idle" | "exporting" | "error">("idle");
  const canvasWrapRef = useRef<HTMLDivElement | null>(null);

  function handleFrame(info: FrameInfo): void {
    setFrameInfo(info);
    if (info.converged && !gain) {
      setGain(computeSeparationGainForSim(sim, mappings, stats, seed));
    }
  }

  // SPEC.md §9: allowed at any point, mid-settle or after — the filename and
  // embedded metadata say plainly which case this frame is (see pngExport.ts).
  async function handleExport(): Promise<void> {
    const canvas = canvasWrapRef.current?.querySelector("canvas");
    if (!canvas) return;
    setExportState("exporting");
    try {
      await exportCanvasAsPng(canvas, {
        seed,
        step: frameInfo.step,
        converged: frameInfo.converged,
        unstable: frameInfo.unstable,
        rowCount: sim.field.n,
        mappings: mappings.map((m) => ({ name: m.name, role: m.role, normalization: m.normalization })),
      });
      setExportState("idle");
    } catch {
      setExportState("error");
    }
  }

  const analysis = useMemo(() => {
    if (!gain || gain.verdict === "insufficient-variance") return null;
    const columns = buildNamedNumericColumns(mappings, stats);
    return analyzeResults(sim.positions, sim.field.n, gain.k, columns);
  }, [gain, sim, mappings, stats]);

  return (
    <>
      <div ref={canvasWrapRef} className="instrument aspect-square w-full overflow-hidden bg-plot" data-testid="canvas-wrap">
        <SimulationCanvas sim={sim} rung={rung} onFrame={handleFrame} data-testid="sim-canvas" />
      </div>
      <div className="mt-3 flex flex-wrap items-center gap-2">
        {/* flex-1 (not justify-between) so the status text's own changing
            width — it re-renders every physics step while settling — never
            shifts the Export button's position. A button sliding around
            every frame is bad for a keyboard/pointer user and, caught by
            trying it live, was ALSO enough to make Playwright's
            actionability check ("must be visible, stable") time out. */}
        <div className="flex-1 font-house-mono text-xs text-ink-3" data-testid="status-line" aria-live="polite">
          {frameInfo.unstable ? (
            <span className="text-amber">simulation became unstable — showing the last stable frame</span>
          ) : frameInfo.converged ? (
            <span>
              Settled after {(frameInfo.step / 60).toFixed(1)}s, {frameInfo.step} steps
            </span>
          ) : (
            <span>Settling… step {frameInfo.step}</span>
          )}
        </div>
        <button
          type="button"
          data-testid="export-png-button"
          onClick={() => void handleExport()}
          disabled={exportState === "exporting"}
          className="chip px-3 py-1.5 disabled:opacity-50"
        >
          {exportState === "exporting" ? "Exporting…" : "Export PNG"}
        </button>
      </div>
      {exportState === "error" && (
        <p className="mt-1 text-xs text-amber" role="alert">
          PNG export failed — try again once the canvas has drawn a frame.
        </p>
      )}
      {gain && (
        <div className="mt-4">{analysis ? <ResultsPanel analysis={analysis} gain={gain} /> : <SeparationGainDisplay gain={gain} />}</div>
      )}
    </>
  );
}

function ReadyTool({ parsed, initialMappings, stats, rung }: { parsed: ParsedTable; initialMappings: ColumnMapping[]; stats: ColumnStats[]; rung: Rung }): React.JSX.Element {
  const [mappings, setMappings] = useState(initialMappings);
  const mappingKey = useMemo(() => mappings.map((m) => `${m.name}:${m.role}:${m.normalization}`).join("|"), [mappings]);
  const budget = RUNG_BUDGETS[rung];
  const built = useMemo(() => buildSimulation(parsed, mappings, stats, DEFAULT_SEED, budget), [parsed, mappings, stats, budget]);

  // 520px, not 360: the mapping table has five columns and a 500px minimum,
  // so a narrower rail made table-fixed overlap its own cells (column name
  // over type, normalization over missing) at every desktop width. Measured
  // at 1440 before and after.
  return (
    <div className="grid grid-cols-1 gap-6 lg:grid-cols-[minmax(0,1fr)_520px]">
      <div className="min-w-0">
        <RunningSimulation key={`${mappingKey}::${rung}`} sim={built.sim} rung={rung} mappings={mappings} stats={built.sampledStats} seed={DEFAULT_SEED} />
        <div className="mt-3">
          <CapabilityLine rung={rung} detecting={false} sampleInfo={built.sampleInfo} />
        </div>
      </div>
      <div className="flex min-w-0 flex-col gap-4">
        <h2 className="font-house-mono text-xs uppercase tracking-[0.14em] text-ink-3">Column mapping</h2>
        <MappingPanel mappings={mappings} stats={stats} onChange={setMappings} />
      </div>
    </div>
  );
}

export function SimulationHost(): React.JSX.Element {
  const [csvText, setCsvText] = useState(DEFAULT_CSV);
  const [draftText, setDraftText] = useState(DEFAULT_CSV);
  const reducedMotion = useReducedMotion();
  const capability = useCapability();
  // M4: the WGSL compute/render path now exists (src/gpu/) — a webgpu-
  // capable visitor gets the real thing. Verified live against this build
  // sandbox's real WebGPU adapter (docs/limitations): navigator.gpu.
  // requestAdapter() resolved null early in the build (M0's probe) but a
  // real adapter+device later in the same session, and SimulationCanvas's
  // webgpu branch was exercised end to end (both the naive and the
  // above-5,000-row spatial-grid path) with zero console errors.
  const rung = resolveRung({ webgpu: capability.webgpu, webgl2: capability.webgl2, reducedMotion });

  const outcome = useParsedDataset(csvText);

  // SPEC.md §10: "This is a real dataset (citation) — paste your own any
  // time" alongside the running demo. Derived from which bundled sample's
  // CSV text is currently loaded (by value, not a separate id) — null when
  // the visitor has pasted something of their own, so no sample copy is
  // shown for data this component never generated.
  const activeSampleId = SAMPLE_DATASETS.find((d) => d.csv === csvText)?.id ?? null;
  const activeSampleNote =
    activeSampleId === "palmer-penguins"
      ? "This is a real dataset (342 penguins, 3 species, Palmer Station Antarctica LTER — CC0) — paste your own any time."
      : activeSampleId === "blobs-3-known"
        ? "This is a synthetic dataset, generated for this demo (3 seeded Gaussian clusters, ground truth = 3 groups) — paste your own any time."
        : activeSampleId === "uncorrelated-random"
          ? "This is a synthetic dataset, generated for this demo — deliberately uncorrelated noise, showing physics find nothing beyond what a 2-axis view already shows — paste your own any time."
          : null;

  return (
    <div className="flex min-w-0 flex-col gap-6">
      {outcome.status === "ready" ? (
        capability.detected || reducedMotion ? (
          <ReadyTool key={csvText} parsed={outcome.parsed} initialMappings={outcome.mappings} stats={outcome.stats} rung={rung} />
        ) : (
          <div className="panel flex aspect-[21/9] w-full items-center justify-center p-8 text-center text-sm text-ink-3">
            Checking device capability…
          </div>
        )
      ) : (
        <div className="panel flex aspect-[21/9] w-full items-center justify-center p-8 text-center text-sm text-ink-2" data-testid="dataset-message">
          {outcome.status === "empty" && "Paste a CSV with a header row to begin."}
          {outcome.status === "parse-error" && outcome.message}
          {outcome.status === "zero-usable-columns" && "No columns here map to a physical property."}
        </div>
      )}

      {outcome.status === "zero-usable-columns" && (
        <ul className="text-xs text-ink-2" data-testid="excluded-columns">
          {outcome.seenColumns.map((c) => (
            <li key={c.name}>
              <code>{c.name}</code>: {c.reason}
            </li>
          ))}
        </ul>
      )}

      <DatasetPicker
        activeCsv={csvText}
        onSelect={(csv) => {
          setCsvText(csv);
          setDraftText(csv);
        }}
      />
      {activeSampleNote && (
        <p className="text-sm text-ink-3" data-testid="active-sample-note">
          {activeSampleNote}
        </p>
      )}

      <div className="flex flex-col gap-2">
        <label htmlFor="csv-input" className="font-house-mono text-xs uppercase tracking-[0.14em] text-ink-3">
          Paste your own CSV
        </label>
        <textarea
          id="csv-input"
          data-testid="csv-textarea"
          className="h-32 w-full rounded-[var(--radius-brand)] border border-rule-strong bg-paper p-2 font-house-mono text-xs"
          value={draftText}
          onChange={(e) => setDraftText(e.target.value)}
          spellCheck={false}
        />
        <div>
          <button
            type="button"
            data-testid="run-button"
            onClick={() => setCsvText(draftText)}
            className="btn-primary"
          >
            Run
          </button>
        </div>
      </div>
    </div>
  );
}
