/**
 * Generates the three bundled sample datasets (SPEC.md §10) into public/samples/:
 *
 *   1. palmer-penguins.csv  — a REAL, small, CC0 dataset with genuine
 *      multi-column structure (species/island + 4 body measurements).
 *      Copied verbatim from the checked-in source at scripts/data/
 *      penguins-source.csv (see that file's own header comment for
 *      provenance) — no live network fetch at generation time, keeping
 *      the "nothing leaves your device" claim clean for the app's own
 *      fixtures (SPEC.md §10) and keeping this script deterministic and
 *      reproducible offline, the same requirement ci:samples-check
 *      depends on (regenerate, then `git diff --exit-code`).
 *   2. blobs-3-known.csv    — synthetic, seed=1 (matching evals/
 *      fixtures.eval.test.ts's own blobs-3-known seed exactly — ONE
 *      generator, so the bundled sample and the CI golden fixture can
 *      never silently drift from each other, per src/core/synthetic.ts's
 *      own header comment).
 *   3. uncorrelated-random.csv — synthetic, seed=2 (matching evals/
 *      fixtures.eval.test.ts's own uncorrelated-random seed).
 *
 * Also writes CREDITS.md, documenting the real dataset's license/citation
 * and stating plainly that the other two are synthetic, generated for this
 * demo (SPEC.md §10.2's own labeling requirement).
 *
 * Also (re)generates src/ui/sample-datasets.ts — the SAME three CSV strings,
 * inlined as TS constants. This is what SimulationHost actually imports: the
 * cold-start dataset (SPEC.md §10, "never an empty waiting-for-input state")
 * must be available synchronously at module-load time, not behind a runtime
 * fetch() that could show a blank/loading flash on a slow connection. The
 * public/samples/*.csv files remain the citable, individually-downloadable
 * originals (and what a "download this dataset" link would point at); this
 * script is the one place both are derived from, so they can never drift.
 *
 * Usage: node scripts/gen-samples.mjs --out=<dir>
 */
import { register } from "tsx/esm/api";
register();

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const { generateBlobs3Known, generateUncorrelatedRandom, toCsv } = await import("../src/core/synthetic.ts");

const BLOBS_SEED = 1; // evals/fixtures.eval.test.ts: generateBlobs3Known(1)
const UNCORRELATED_SEED = 2; // evals/fixtures.eval.test.ts: generateUncorrelatedRandom(2)

const CREDITS_MD = `# Sample dataset credits

## 1. palmer-penguins.csv — real data

Bill length/depth, flipper length, body mass, species, and island for 342
penguins across three species (Adelie, Chinstrap, Gentoo) at three islands in
the Palmer Archipelago, Antarctica. Rows with any missing measurement were
dropped; the \`sex\` and \`year\` columns were dropped as not central to this
demo (kept: \`species\`, \`island\`, \`bill_length_mm\`, \`bill_depth_mm\`,
\`flipper_length_mm\`, \`body_mass_g\`).

- **Source:** Gorman KB, Williams TD, Fraser WR (2014). PLoS ONE 9(3): e90081.
  Data collected by Dr. Kristen Gorman and the Palmer Station Long Term
  Ecological Research (LTER) Program, U.S. LTER Network. Distributed as the
  \`palmerpenguins\` R package by Allison Horst, Alison Hill, and Kristen
  Gorman: <https://allisonhorst.github.io/palmerpenguins/>.
- **License:** CC0 1.0 Universal (public domain dedication).
- **Modification from source:** row-filtered and column-subset only (see
  above); no values altered. See \`scripts/gen-samples.mjs\` and
  \`scripts/data/penguins-source.csv\` for the exact, reproducible steps.

## 2. blobs-3-known.csv — synthetic, generated for this demo

Three Gaussian clusters in 5 numeric dimensions, seed \`${String(BLOBS_SEED)}\`,
generated by \`src/core/synthetic.ts\`'s \`generateBlobs3Known\`. Not real-world
data — a known-ground-truth fixture, labeled as such on-page. The identical
generator call backs this file's CI golden fixture (\`evals/
fixtures.eval.test.ts\`), so the bundled sample and the tested behavior can
never silently drift apart.

## 3. uncorrelated-random.csv — synthetic, generated for this demo

180 rows of uniform random noise in 5 numeric dimensions, seed
\`${String(UNCORRELATED_SEED)}\`, generated by \`src/core/synthetic.ts\`'s
\`generateUncorrelatedRandom\`. Deliberately structureless — demonstrates the
death-condition guard (SPEC.md §10 sample #3): physics is expected to find
nothing here beyond what a 2-axis view already shows, and the page says so
plainly rather than overclaiming.
`;

async function main() {
  const args = Object.fromEntries(
    process.argv.slice(2).map((a) => {
      const [k, v] = a.replace(/^--/, "").split("=");
      return [k, v ?? true];
    })
  );
  const outDir = args.out ?? "public/samples";
  mkdirSync(outDir, { recursive: true });

  const penguinsSource = readFileSync(join(__dirname, "data", "penguins-source.csv"), "utf8");
  writeFileSync(join(outDir, "palmer-penguins.csv"), penguinsSource);

  const blobs = generateBlobs3Known(BLOBS_SEED);
  writeFileSync(join(outDir, "blobs-3-known.csv"), toCsv(blobs.rows));

  const uncorrelated = generateUncorrelatedRandom(UNCORRELATED_SEED);
  writeFileSync(join(outDir, "uncorrelated-random.csv"), toCsv(uncorrelated));

  writeFileSync(join(outDir, "CREDITS.md"), CREDITS_MD);

  const blobsCsv = toCsv(blobs.rows);
  const uncorrelatedCsv = toCsv(uncorrelated);
  const dataModule = `// GENERATED FILE — do not hand-edit. Produced by scripts/gen-samples.mjs
// (the same script that writes public/samples/*.csv); run \`pnpm gen:samples\`
// after changing scripts/data/penguins-source.csv or the synthetic seeds
// below, then commit the diff. ci:samples-check fails CI on drift.
//
// Inlined as TS constants (rather than fetched from public/samples/ at
// runtime) so the cold-start dataset is available synchronously at
// module-load time — SPEC.md §10 requires the page load directly into
// sample #1 already mid-settle, never an empty "waiting for input" state,
// which a runtime fetch() could momentarily violate on a slow connection.

export const PALMER_PENGUINS_CSV = ${JSON.stringify(penguinsSource)};
export const BLOBS_3_KNOWN_CSV = ${JSON.stringify(blobsCsv)};
export const UNCORRELATED_RANDOM_CSV = ${JSON.stringify(uncorrelatedCsv)};

export interface SampleDataset {
  id: string;
  label: string;
  description: string;
  csv: string;
}

export const SAMPLE_DATASETS: SampleDataset[] = [
  {
    id: "palmer-penguins",
    label: "Palmer Penguins (real data)",
    description: "342 penguins, 3 species, Palmer Station Antarctica LTER — CC0.",
    csv: PALMER_PENGUINS_CSV,
  },
  {
    id: "blobs-3-known",
    label: "3 known clusters (synthetic)",
    description: "Synthetic, generated for this demo — 3 seeded Gaussian clusters in 5 dimensions.",
    csv: BLOBS_3_KNOWN_CSV,
  },
  {
    id: "uncorrelated-random",
    label: "Uncorrelated noise (synthetic)",
    description: "Synthetic, generated for this demo — deliberately structureless, tests the death-condition guard.",
    csv: UNCORRELATED_RANDOM_CSV,
  },
];
`;
  const dataModulePath = join(__dirname, "..", "src", "ui", "sample-datasets.ts");
  mkdirSync(dirname(dataModulePath), { recursive: true });
  writeFileSync(dataModulePath, dataModule);

  console.log(`gen-samples: wrote palmer-penguins.csv, blobs-3-known.csv, uncorrelated-random.csv, CREDITS.md -> ${outDir}`);
  console.log(`gen-samples: wrote ${dataModulePath}`);
}

await main();
